baseURL = 'https://embici.github.io/'
languageCode = 'en-us'
title = 'Embici Blog'
theme = 'anatole'

[params]
  env = "production"
  title = "Embici Blog"
  description = "A personal blog about technology and life"
  keywords = ["blog", "technology", "personal"]
  # Anatole theme specific parameters
  featured_image = "/images/header.jpg"
  featured_image_alt = "Blog header image"
  rss_icon = true
  favicon = "/favicon.ico"
  # Social links
  [[params.social]]
    name = "github"
    url = "https://github.com/embici"
  [[params.social]]
    name = "twitter"
    url = "https://twitter.com/embici"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = -100
    pre = "home"
  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = -90
    pre = "list"
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = -80
    pre = "user" 