baseURL = 'https://embici.github.io/'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
theme = 'anatole'

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    title = "Embici Blog"
    [languages.en.params]
      subtitle = "A personal blog about technology and life"
      keywords = ["blog", "technology", "personal"]
      featured_image = "/images/header.jpg"
      featured_image_alt = "Blog header image"
      rss_icon = true
      favicon = "/favicon.ico"
      [[languages.en.params.social]]
        name = "github"
        url = "https://github.com/embici"
      [[languages.en.params.social]]
        name = "twitter"
        url = "https://twitter.com/embici"
    [[languages.en.menu.main]]
      identifier = "home"
      name = "Home"
      url = "/en/"
      weight = -100
      pre = "home"
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/en/posts/"
      weight = -90
      pre = "list"
    [[languages.en.menu.main]]
      identifier = "about"
      name = "About"
      url = "/en/about/"
      weight = -80
      pre = "user"

  [languages.es]
    languageName = "Español"
    weight = 2
    title = "Embici Blog"
    [languages.es.params]
      subtitle = "Un blog personal sobre tecnología y vida"
      keywords = ["blog", "tecnología", "personal"]
      featured_image = "/images/header.jpg"
      featured_image_alt = "Imagen de encabezado del blog"
      rss_icon = true
      favicon = "/favicon.ico"
      [[languages.es.params.social]]
        name = "github"
        url = "https://github.com/embici"
      [[languages.es.params.social]]
        name = "twitter"
        url = "https://twitter.com/embici"
    [[languages.es.menu.main]]
      identifier = "home"
      name = "Inicio"
      url = "/es/"
      weight = -100
      pre = "home"
    [[languages.es.menu.main]]
      identifier = "posts"
      name = "Artículos"
      url = "/es/posts/"
      weight = -90
      pre = "list"
    [[languages.es.menu.main]]
      identifier = "about"
      name = "Sobre Mí"
      url = "/es/about/"
      weight = -80
      pre = "user"

  [languages.pt]
    languageName = "Português"
    weight = 3
    title = "Embici Blog"
    [languages.pt.params]
      subtitle = "Um blog pessoal sobre tecnologia e vida"
      keywords = ["blog", "tecnologia", "pessoal"]
      featured_image = "/images/header.jpg"
      featured_image_alt = "Imagem de cabeçalho do blog"
      rss_icon = true
      favicon = "/favicon.ico"
      [[languages.pt.params.social]]
        name = "github"
        url = "https://github.com/embici"
      [[languages.pt.params.social]]
        name = "twitter"
        url = "https://twitter.com/embici"
    [[languages.pt.menu.main]]
      identifier = "home"
      name = "Início"
      url = "/pt/"
      weight = -100
      pre = "home"
    [[languages.pt.menu.main]]
      identifier = "posts"
      name = "Artigos"
      url = "/pt/posts/"
      weight = -90
      pre = "list"
    [[languages.pt.menu.main]]
      identifier = "about"
      name = "Sobre Mim"
      url = "/pt/about/"
      weight = -80
      pre = "user"

[params]
  env = "production"
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true 